[package]
name = "pod_racing_contract"
type = "contract"
authors = [ "" ]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-nr/", tag = "v4.0.0-nightly.20260204", directory = "aztec" }
